### ISSUE TITLE
Could you publish this role to ansible galaxy?

### ISSUE THREAD

**Issue by 030** [kbrebanov/ansible-rabbitmq#2] opened 2016-08-12 09:34 UTC

**Comment by kbrebanov** [comment] 2016-08-13 13:05
This role has already been published to Ansible Galaxy.

The issue is that the current version of Ansible Galaxy does not properly parse the contents of the README file. The issue seems to have been resolved in their QA environment but it has not been pushed to their production environment yet.

For more info, you can check out:
https://github.com/ansible/galaxy-issues/issues/156

**Comment by kbrebanov** [comment] 2016-08-13 13:09
It already has been published to Ansible Galaxy.

https://galaxy.ansible.com/kbrebanov/rabbitmq/

**Closed as completed** 2016-08-13 13:15 UTC
Labels: question
